# Smart Expense Categorizer — ML Model

Goal:
Train an NLP-based classifier that predicts a normalized expense category TF-IDF
based on item descriptions.

Input: Item (text)
Output: Category (normalized)

In [2]:
import numpy as np
import pandas as pd

# Visualization
import matplotlib.pyplot as plt
import seaborn as sns

# Text processing & ML
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# Models (you will choose one later)
from sklearn.naive_bayes import MultinomialNB
from sklearn.linear_model import LogisticRegression

# Utilities
import re
# Built-in Python module
# Used for text cleaning
# No install needed
import joblib
# Used to save ML models to disk
# Faster & safer than pickle for ML objects
# save trained model
# load it again in backend

In [3]:
RANDOM_STATE = 42
TEST_SIZE = 0.2
VAL_SIZE = 0.2

RANDOM_STATE = 42

# Makes results reproducible
# Same split every time
# Industry standard
# “Why 42?”
# Answer:
# “Any fixed number works; it ensures reproducibility.”

In [4]:
DATA_PATH = "../data/raw/primary_spending_patterns_detailed.csv"

df = pd.read_csv(DATA_PATH)
df.head()

,Customer ID,Category,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,CUST_0159,Groceries,Milk,1,1.28,1.28,Debit Card,Mobile App,2024-11-13
1,CUST_0017,Friend Activities,Dinner with Friends,2,74.69,149.39,Debit Card,In-store,2023-05-04
2,CUST_0094,Housing and Utilities,Water Bill,1,76.06,76.06,Digital Wallet,Mobile App,2023-12-16
3,CUST_0162,Fitness,Yoga Class,5,11.24,56.18,Cash,In-store,2024-01-28
4,CUST_0129,Gifts,Flowers,3,43.71,131.12,Debit Card,In-store,2023-07-28

In [5]:
df[["Item", "Category"]].head()

                  Item               Category
0                 Milk              Groceries
1  Dinner with Friends      Friend Activities
2           Water Bill  Housing and Utilities
3           Yoga Class                Fitness
4              Flowers                  Gifts

In [6]:
category_mapping = {
'Groceries':'Food',
'Food':'Food',
'Shopping':'Shopping',
'Subscriptions':'Bills',
'Housing and Utilities':'Bills',
'Transportation':'Transport',
'Hobbies':'Entertainment',
'Friend Activities':'Entertainment',
'Travel':'Entertainment',
'Personal Hygiene':'Personal',
'Fitness':'Personal',
'Medical/Dental':'Other',
'Gifts':'Other',
}

In [7]:
df['Normalized Category'] = df['Category'].map(category_mapping)

In [8]:
# To check if after Normalization any data is null
print(df[df['Normalized Category'].isnull()])

Empty DataFrame
Columns: [Customer ID, Category, Item, Quantity, Price Per Unit, Total Spent, Payment Method, Location, Transaction Date, Normalized Category]
Index: []

In [9]:
df['Normalized Category'].value_counts()

Normalized Category
Entertainment    2240
Food             1593
Personal         1567
Other            1559
Bills            1504
Shopping          775
Transport         762
Name: count, dtype: int64

In [10]:
df['Normalized Category'].nunique()

7

In [11]:
def clean_text(text):
    """
    Basic text cleaning for expense item descriptions
    """
    text = text.lower()
    text = re.sub(r"[^a-zA-Z0-9\s]", "", text)  # remove punctuation
    text = re.sub(r"\s+", " ", text).strip()   # normalize spaces
    return text

In [12]:
df['clean_item'] = df['Item'].apply(clean_text)

In [13]:
df[['Item', 'clean_item']].sample(10)

                   Item         clean_item
9475          Taxi/Uber           taxiuber
3422          Fast Food          fast food
9772  Streaming Service  streaming service
6326         Toothpaste         toothpaste
2308            Flowers            flowers
6545  Streaming Service  streaming service
3874      Movie Tickets      movie tickets
8638       Art Supplies       art supplies
8342         Hotel Stay         hotel stay
696       Dentist Visit      dentist visit

In [14]:

X = df['clean_item']   # text input
y = df['Normalized Category']  # labels

### Step 1: Train + Temp

In [15]:
X_train, X_temp, y_train, y_temp = train_test_split(
    X,
    y,
    test_size=0.4,
    random_state=42,
    stratify=y
)

stratify=y <br>
If your target variable `y` is **categorical / classification labels**, stratification ensures that:

- `X_train` and `X_temp` have **roughly the same percentage of each class**
- You don’t end up with one split missing a class or being heavily imbalanced

### Step 2: Validation + Test

In [16]:
X_val, X_test, y_val, y_test = train_test_split(
    X_temp,
    y_temp,
    test_size=0.5,
    random_state=42,
    stratify=y_temp
)

In [20]:
# To Test the proportions
print(y_train.value_counts(normalize=True))
print(y_val.value_counts(normalize=True))
print(y_test.value_counts(normalize=True))

Normalized Category
Entertainment    0.224000
Food             0.159333
Personal         0.156667
Other            0.156000
Bills            0.150333
Shopping         0.077500
Transport        0.076167
Name: proportion, dtype: float64
Normalized Category
Entertainment    0.2240
Food             0.1590
Personal         0.1565
Other            0.1560
Bills            0.1505
Shopping         0.0775
Transport        0.0765
Name: proportion, dtype: float64
Normalized Category
Entertainment    0.2240
Food             0.1595
Personal         0.1570
Other            0.1555
Bills            0.1505
Shopping         0.0775
Transport        0.0760
Name: proportion, dtype: float64

In [21]:
print(y_train.value_counts())
print(y_val.value_counts())
print(y_test.value_counts())

Normalized Category
Entertainment    1344
Food              956
Personal          940
Other             936
Bills             902
Shopping          465
Transport         457
Name: count, dtype: int64
Normalized Category
Entertainment    448
Food             318
Personal         313
Other            312
Bills            301
Shopping         155
Transport        153
Name: count, dtype: int64
Normalized Category
Entertainment    448
Food             319
Personal         314
Other            311
Bills            301
Shopping         155
Transport        152
Name: count, dtype: int64

In [22]:
vectorizer = TfidfVectorizer(
    ngram_range=(1, 2),   # unigrams + bigrams
    min_df=2,             # ignore super rare words
    max_df=0.9            # ignore super common words
)

In [23]:
X_train_tfidf = vectorizer.fit_transform(X_train)
X_val_tfidf = vectorizer.transform(X_val)
X_test_tfidf = vectorizer.transform(X_test)

In [24]:
X_train.iloc[0]

'hotel stay'

In [25]:
X_train_tfidf[0].toarray()

array([[0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.57735027, 0.57735027, 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.57735027, 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        ]])

In [26]:
from sklearn.naive_bayes import MultinomialNB

nb_model = MultinomialNB()

nb_model.fit(X_train_tfidf, y_train)

MultinomialNB()

In [27]:
y_val_pred = nb_model.predict(X_val_tfidf)

from sklearn.metrics import accuracy_score, classification_report

print("Validation Accuracy:", accuracy_score(y_val, y_val_pred))
print(classification_report(y_val, y_val_pred))

Validation Accuracy: 1.0
               precision    recall  f1-score   support

        Bills       1.00      1.00      1.00       301
Entertainment       1.00      1.00      1.00       448
         Food       1.00      1.00      1.00       318
        Other       1.00      1.00      1.00       312
     Personal       1.00      1.00      1.00       313
     Shopping       1.00      1.00      1.00       155
    Transport       1.00      1.00      1.00       153

     accuracy                           1.00      2000
    macro avg       1.00      1.00      1.00      2000
 weighted avg       1.00      1.00      1.00      2000

The dataset is synthetic and highly structured, which results in near-perfect accuracy.


In real-world data, performance would be lower due to noisy and unseen descriptions.

In [28]:
y_test_pred = nb_model.predict(X_test_tfidf)

print("Test Accuracy:", accuracy_score(y_test, y_test_pred))
print(classification_report(y_test, y_test_pred))

Test Accuracy: 1.0
               precision    recall  f1-score   support

        Bills       1.00      1.00      1.00       301
Entertainment       1.00      1.00      1.00       448
         Food       1.00      1.00      1.00       319
        Other       1.00      1.00      1.00       311
     Personal       1.00      1.00      1.00       314
     Shopping       1.00      1.00      1.00       155
    Transport       1.00      1.00      1.00       152

     accuracy                           1.00      2000
    macro avg       1.00      1.00      1.00      2000
 weighted avg       1.00      1.00      1.00      2000

In [29]:
sample_items = [
    "metro ticket",
    "electricity payment",
    "burger and fries",
    "netflix subscription",
    "gym fee",
    "doctor consultation"
]

sample_clean = [clean_text(x) for x in sample_items]
sample_vec = vectorizer.transform(sample_clean)

nb_model.predict(sample_vec)

array(['Entertainment', 'Bills', 'Entertainment', 'Entertainment',
       'Bills', 'Other'], dtype='<U13')

The baseline Naive Bayes model performs perfectly on the synthetic dataset, but when tested on unseen real-world phrases, we observe semantic drift. This highlights the limitation of training on structured synthetic data and motivates future retraining on real transaction descriptions.

In [30]:
import os

ARTIFACTS_DIR = "../artifacts"
os.makedirs(ARTIFACTS_DIR, exist_ok=True)
# Create the folder if it doesn’t exist

In [31]:
import joblib

joblib.dump(vectorizer, f"{ARTIFACTS_DIR}/vectorizer.pkl")

['../artifacts/vectorizer.pkl']

In [32]:
joblib.dump(nb_model, f"{ARTIFACTS_DIR}/model.pkl")

['../artifacts/model.pkl']

<!-- Later, in FastAPI or another script:

vectorizer = joblib.load("artifacts/vectorizer.pkl")

model = joblib.load("artifacts/model.pkl") -->

Later, in FastAPI or another script:

vectorizer = joblib.load("artifacts/vectorizer.pkl")

model = joblib.load("artifacts/model.pkl")

text = ["metro ticket"]

text_clean = [clean_text(x)]

vec = vectorizer.transform(text_clean)

model.predict(vec)

In [37]:
from sklearn.linear_model import LogisticRegression

log_reg = LogisticRegression(
    max_iter=1000,        # important for text data
    random_state=42,
)

log_reg.fit(X_train_tfidf, y_train)

LogisticRegression(max_iter=1000, random_state=42)

In [38]:
y_val_pred_lr = log_reg.predict(X_val_tfidf)

print("Logistic Regression - Validation Accuracy:",
      accuracy_score(y_val, y_val_pred_lr))

print(classification_report(y_val, y_val_pred_lr))

Logistic Regression - Validation Accuracy: 1.0
               precision    recall  f1-score   support

        Bills       1.00      1.00      1.00       301
Entertainment       1.00      1.00      1.00       448
         Food       1.00      1.00      1.00       318
        Other       1.00      1.00      1.00       312
     Personal       1.00      1.00      1.00       313
     Shopping       1.00      1.00      1.00       155
    Transport       1.00      1.00      1.00       153

     accuracy                           1.00      2000
    macro avg       1.00      1.00      1.00      2000
 weighted avg       1.00      1.00      1.00      2000

In [39]:
y_test_pred_lr = log_reg.predict(X_test_tfidf)

print("Logistic Regression - Test Accuracy:",
      accuracy_score(y_test, y_test_pred_lr))

print(classification_report(y_test, y_test_pred_lr))

Logistic Regression - Test Accuracy: 1.0
               precision    recall  f1-score   support

        Bills       1.00      1.00      1.00       301
Entertainment       1.00      1.00      1.00       448
         Food       1.00      1.00      1.00       319
        Other       1.00      1.00      1.00       311
     Personal       1.00      1.00      1.00       314
     Shopping       1.00      1.00      1.00       155
    Transport       1.00      1.00      1.00       152

     accuracy                           1.00      2000
    macro avg       1.00      1.00      1.00      2000
 weighted avg       1.00      1.00      1.00      2000

In [40]:
sample_vec = vectorizer.transform(sample_clean)

print("Naive Bayes:", nb_model.predict(sample_vec))
print("Logistic Regression:", log_reg.predict(sample_vec))

Naive Bayes: ['Entertainment' 'Bills' 'Entertainment' 'Entertainment' 'Bills' 'Other']
Logistic Regression: ['Entertainment' 'Bills' 'Food' 'Food' 'Bills' 'Other']

In [41]:
feature_names = vectorizer.get_feature_names_out()

def top_words_per_class(model, feature_names, class_label, top_n=10):
    class_index = list(model.classes_).index(class_label)
    coef = model.coef_[class_index]

    top_positive_indices = np.argsort(coef)[-top_n:]
    
    return [(feature_names[i], coef[i]) for i in reversed(top_positive_indices)]

In [42]:
top_words_per_class(log_reg, feature_names, "Food")

[('coffee', np.float64(4.053706097705797)),
 ('vegetables', np.float64(3.5044353618761597)),
 ('chicken', np.float64(3.4854127386736096)),
 ('bread', np.float64(3.465855157284624)),
 ('fruits', np.float64(3.425006612776511)),
 ('snacks', np.float64(3.403644703077914)),
 ('meat', np.float64(3.3353161192624894)),
 ('milk', np.float64(3.285739953963071)),
 ('fast', np.float64(2.378717691875821)),
 ('fast food', np.float64(2.378717691875821))]

In [43]:
top_words_per_class(log_reg, feature_names, "Transport")

[('gas', np.float64(5.333401173753359)),
 ('repair', np.float64(3.8552065063457333)),
 ('car repair', np.float64(3.8552065063457333)),
 ('public transit', np.float64(3.097190786406494)),
 ('public', np.float64(3.097190786406494)),
 ('transit', np.float64(3.097190786406494)),
 ('car', np.float64(1.2001032705386887)),
 ('electricity bill', np.float64(-0.12945108420928314)),
 ('electricity', np.float64(-0.12945108420928314)),
 ('water bill', np.float64(-0.14209693483561714))]

In [44]:
top_words_per_class(log_reg, feature_names, "Bills")

[('bill', np.float64(5.05343008396425)),
 ('magazine', np.float64(4.578191094812423)),
 ('rent', np.float64(4.444631993332577)),
 ('gas bill', np.float64(2.812698708228469)),
 ('membership', np.float64(2.643219860991502)),
 ('gym membership', np.float64(2.643219860991502)),
 ('gym', np.float64(2.643219860991502)),
 ('service', np.float64(2.6209119862258365)),
 ('streaming', np.float64(2.6209119862258365)),
 ('streaming service', np.float64(2.6209119862258365))]

In [45]:
joblib.dump(nb_model, f"{ARTIFACTS_DIR}/expense_classifier_nb.pkl")
joblib.dump(vectorizer, f"{ARTIFACTS_DIR}/tfidf_vectorizer.pkl")
joblib.dump(log_reg, f"{ARTIFACTS_DIR}/expense_classifier_lr.pkl")

['../artifacts/expense_classifier_lr.pkl']